#!/bin/bash

# Ensure script is run with sudo or as root
if [ "$(id -u)" -ne 0 ]; then
echo "This script must be run with sudo or as root. Please try again."
exit 1
fi

# Ensure packages file exists
if [ ! -f packages ]; then
  echo "Packages file not found, please ensure it exists in the same folder as this script"
  exit 1
fi

# Sync repository database, update system packages
pacman -Syu --noconfirm

# Install each package listed in packages file
for package in $(cat packages); do
  pacman -S --needed "$package" --noconfirm
done
